---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: pyapp-istio-test
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80  # The service port
    targetPort: 80  # The container port

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: nginx-virtualservice
  namespace: pyapp-istio-test
spec:
  selector:
    istio: aks-istio-ingressgateway-external
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

#---
#apiVersion: networking.istio.io/v1beta1
#kind: VirtualService
#metadata:
#  name: nginx
#  namespace: pyapp-istio-test
#spec:
#  hosts:
#  - "*"
#  gateways:
#  - nginx-gateway
#  http:
#  - match:
#    - uri:
#        prefix: /
#  - route:
#    - destination:
#        host: nginx-service
#        port:
#          number: 80

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-virtualservice
  namespace: pyapp-istio-test
spec:
  hosts:
  - "*"
  gateways:
  -  nginx-virtualservice # Use istio-system/aks-istio-ingressgateway-internal for internal access
  http:
  #- match:
  #  - uri:
  #      prefix: /
  - route:
    - destination:
        host: nginx-service.pyapp-istio-test.svc.cluster.local
        port:
          number: 80

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: nginx-destinationrule
  namespace: pyapp-istio-test
spec:
  host: nginx-service.pyapp-istio-test.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
      #simple: RANDOM
      #tls:
      #  mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1