---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: pyapp-istio-test
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80  # The service port
    targetPort: 80  # The container port
